name = "Blueprint"
author = "ItsPercent"
version = "3.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c314edbb49756befa8e94a0f2fdf971741f30616340500ad3a95fb866e25a9e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
