name = "Blueprint"
author = "ItsPercent"
version = "3.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd18afbb6148129e3ecb07353cc700f6b327c7284020213bfca26910297cea21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
