name = "Blueprint"
author = "ItsPercent"
version = "3.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3223e486203d8f4b4a87dbb29722519e7e545c38c0a0554c155cd40edaab3006"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
