hash-format = "sha256"

[[files]]
file = "config/create-client.toml"
hash = "df7ce62647f75fb1fc75a0edff62469baf60fed420005862e1026816166b6da4"

[[files]]
file = "config/create_cyber_goggles.toml"
hash = "d44c11043b0904fbc0f24b8bb1d542fd4b5c1f604bed95e4192e1bcffef2b445"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "c27bf0985627c1b77b46557aac4dc6783994de61c3d10ea46fa034af867c98fb"

[[files]]
file = "config/paxi/datapack_load_order.json"
hash = "d0aaf3172f34275479f0669aa5b0a94b85788ae638f3062b948ec49d31c38293"

[[files]]
file = "config/paxi/resourcepack_load_order.json"
hash = "d0aaf3172f34275479f0669aa5b0a94b85788ae638f3062b948ec49d31c38293"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/texts/splashes.txt"
hash = "2764ac4e19e44298866f6eca44198ea42d41bda1da54fdffdbce1d237e3190da"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/sprites/hud/hotbar_selection.png"
hash = "1ec465c5745f786be4757af9bc3ba74cf40aee4d32089206352c66a1d4df7ffa"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/title/background/panorama_0.png"
hash = "4d7afea83d5ee84285ae6f6171fd66cd1a067529d1846d7e590ce013f57b2826"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/title/background/panorama_1.png"
hash = "9ba288eb371691dc29ce908e9cd0bc301299c72d96db1a0a48bf777880fd9d01"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/title/background/panorama_2.png"
hash = "4b4430cd9af55694faff728359eac6131f2400825409ab69a63063da5ae5bd02"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/title/background/panorama_3.png"
hash = "39700f06a8134d6f453ddd4ebdf6410af1b95bfbfc040ced5ac2a44fcc27f76c"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/title/background/panorama_4.png"
hash = "35f5d35f844afaa8c2e1efe4e5c433c2e5a112cdad82541db4a5aaa48a022b6c"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/assets/minecraft/textures/gui/title/background/panorama_5.png"
hash = "f13a75868373d6bfd8374cb0e73cef788443260247187da7ef078a226729d004"

[[files]]
file = "config/paxi/resourcepacks/Blueprint Overrides/pack.mcmeta"
hash = "4a86db0a940fc04bf738b8ebbcef7c50221c9f7c0cd24ff5c43a3d116202f77e"

[[files]]
file = "config/paxi/resourcepacks/Unnamed_Create_Computers_Resource_Pack.zip"
hash = "432ecfa4cc26d8ffcabfe18afe2028845416fc82c3b6cc930a4443eb0d795f19"

[[files]]
file = "config/supplementaries-client.toml"
hash = "12642ea9a7205959953198e7b124c12336dc6de7df1838f61d856329ae35ace8"

[[files]]
file = "kubejs/config/client.json"
hash = "f38d326943014d6906916a9387c75e2bfd609fce10e92049d76a395c5775b6f1"

[[files]]
file = "kubejs/config/common.json"
hash = "e00a67922942660d77c213379b5128a46c5abc894178b0be04006d325ff5f6b3"

[[files]]
file = "kubejs/config/defaultoptions.txt"
hash = "58b30f6051c9c223f5d5bfb382617830bda874a8b1451f6b24eb309cde982687"

[[files]]
file = "kubejs/config/pack-icon.png"
hash = "d0d4143d0765fcb3dbb3f22e7ae54feb26ff1224f50f6c07a90cc02ce844c804"

[[files]]
file = "kubejs/config/web_server.json"
hash = "ec2db3ce65eb59f1f813a3dd5d048fd7ef08b3de1f45c80c958189a2a72f4ced"

[[files]]
file = "mods/amendments.pw.toml"
hash = "8b9bd5d12a7068c334ab4ad626a9a86e70302cda90885daa531bfa842e8b29c5"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/backport-copper-age.pw.toml"
hash = "fe040e6cd7b69888e9070ecef8f702bb111bf7771547cfac5ace5eedc023e82b"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b8c29dac6fb7c1cf18ca53b7a96c6c4854307999b77a751e803bdd9650a125e0"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "c45dce6b9e52796c0606ff222efa5833fd1d420fa67e7a8f26852196b80f6fa5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/colorwheel-patcher.pw.toml"
hash = "ae8d380124a4c6e2c34d0d6d6fcd06f1ed4428fea1e74b95013b5155fdf7e623"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "ffaabe4fa9cff6931ec743ae36a053b4619f1ed30d2d80114c2efefd08ab13a4"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "d8480ee1f6ae58fa389e502108bcde4936ca326d6dc2f1608b9af9ac141cb35a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "4d5ba0ec7ea7abf0ef76f3f08853bd7c886eec95b1795cbeacaba8bc608e2913"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "853df4ab2418f347cbb1e3b4ca6c82b2a517a8e4e8ccabcd42c27e3496707a32"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "9eb4f3e7a5a83c588e0caa676d91597c18f2c8004c9e57a10e72859e474fa0e5"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
hash = "5021b4a0f5474201447787ebe98a5d6cf3d18b10e06fe64f726608e4739e8a9f"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "aa8711ff3f1d590b8c3e4e092927e5a697d585e21c52107ddc559c93ffebdaed"
metafile = true

[[files]]
file = "mods/create-cyber-goggles.pw.toml"
hash = "6989fbef26866dff47b04fe1253b54c53ba5bcfe30f35192cf4ee96e125f572b"
metafile = true

[[files]]
file = "mods/create-radars.pw.toml"
hash = "d329779921574e5a4709ee468955af18c84546a2be55d13a0e49ca0fc88b0a6f"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "b13bad02617c5c0b39dede935d46bbf9755e66581087254372a12364b75df2b9"
metafile = true

[[files]]
file = "mods/create-tweaked-controllers.pw.toml"
hash = "aba70a0cd8e2169d87508bcf587b8f59cebd0ea466b2fd873a0ca21f9a02ade3"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "ac4cbd7785b8c70de4037162d6626910633e6b997c957e90de961316716e8402"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "9533bf5a38bb96fe67df246f0c2ac5ce26604c375bfc069487a715e44fabecb9"
metafile = true

[[files]]
file = "mods/dark-mode-everywhere.pw.toml"
hash = "6ce209c1fb04329eb79b5782b6655f5ae6800b4d0be3d412fff5cd75ae973166"
metafile = true

[[files]]
file = "mods/draggable-lists.pw.toml"
hash = "bfe939f563e561df6410a82e9f36ec3793634e470c9b729088072ff8824018ac"
metafile = true

[[files]]
file = "mods/drive-by-wire.pw.toml"
hash = "0660a4f8e5ea24c70144aec20b47e8f39e9340b6576421650cc71ddcdee0cf4c"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "b4e39eaf05f752f5160666b4fc9d4488cd51edebff597f32bb14e139dd5e085e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "25d3f272639cef595de126a2c51faff793dc03bcde63ef060e1277c315583ce7"
metafile = true

[[files]]
file = "mods/extra-gauges.pw.toml"
hash = "edb1ddea9ee012f7dffd5c4bf9b3f6b9d33a08bdd029bbf30352ce07a80c5a4c"
metafile = true

[[files]]
file = "mods/fast-item-frames.pw.toml"
hash = "13688d053fea645191bb62d3ba6d2ad6e9e0a70bb15d9f9208279232178d5be6"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/flerovium.pw.toml"
hash = "57b4b547bb2a5236b6ff1c5b4feedc8853891d7786751f6b75397319794fd301"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5ccedc16130668600dec39a19609afd33ea1f2a0e92f737b4369c117b7276160"
metafile = true

[[files]]
file = "mods/interactive.pw.toml"
hash = "7442eedee93f3797e9bedce849d5a41bdb4b8a26255ee47090caaaee961887f1"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "f8312021fd88a4952e1d50a2f156fab65314f87658d7153efc56be76a422d5cd"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b0441c2b5bb6ff680d97eac28d95847f0d4dbee34d1d42d897997b500acd44ca"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "b6ed220c9069f60704dbfe19fd55c976ca56ada35bcb6918c4ad226cd842b99c"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "ab170eabaeec3e80c59e850a7d8aee32edfffd6a1e40e2c2f44575c69d122054"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "186909f73870979511db893fca2e2a318b311361f168d425ba0e58fc539188ee"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "32ebc8e9c6d09c9f460f0f2815a6e5d5d68c73c75eb912b474c210689a9809f1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "c18dd089c44103b56f8edcbd41a071e41a1fcd46094b2c93df5cc5f07853f18b"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4c96dddf8b3d5bf5ea331459b13d23d7d37332dea2275c00ef755420a66676c4"
metafile = true

[[files]]
file = "mods/ntrials.pw.toml"
hash = "03019ce1c2ba317c45faed184e83a078c0eaf689ba7bd504323f27b5decb25d8"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "be48890d990e03c639c5636c79bfa74bbd531c49a80487507984899c386a0bd9"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "131e4f8e6ea05f47b2167852ad319d15a004e951b49aba54cbb6306570319cea"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "ae4d739bbdb025651a884093de72addac0865525b39e603fb575031a59987763"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "5b92406160d9ea8a61ddf111caaecb7f6283678e2c40b08b72dce3eeaf20dc96"
metafile = true

[[files]]
file = "mods/rpl.pw.toml"
hash = "93128d85ae0b3be9c8248b09f3a63ed88c746568480cc7e9a8e2a9b4bd13477c"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "b97a311aeaf633716450ac7ac644d8cdbc4b9731840ad1a08f9957a80de586e1"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "82bb7cd6c8b68bb1831bb7c374bd316b6403cd01195d582f19c31076c908953a"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "75a60e6b443b351b7a4a78ffce7c71e44b3e20ca10c374aea1de516c785d6e2d"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "a83de63387c9fd0afedb93c8a1da851c6fb6dc72e4fb09c24b145b23fc1bb549"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "974af7bd8b20941d615aa6d37f522da34f62d81ddee97ccfad3c458b5db8ece5"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "53b00436579bd2ea920ef8ae8b1464cb4744dbfd21055d8a3f4768019b78e5bc"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "24332be98ab9c9250af31714c85785b6790bddc2def491e1ba6d249defa714ae"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "beca04dfa133d41a193ecd5566a4448beeacc7db078d17d4f0149d0856168ec0"
metafile = true

[[files]]
file = "mods/vmod.pw.toml"
hash = "16df875d4c8a6e2394556ab78ae8fa932078e32713d3d948861e7245adc98db7"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "bd1dc13316e2aa9b56c89e7e974057f8da8d6bbfe707ba4210109fc612b782e3"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "dd9c8d955749815ea13a1e500711926fd631bab441ceda04994ac84d1cdd52a6"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "c610e4f3a315259f44c6c2ce05503e93c7525a43a21d13f0e0661062cb82bede"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true

[[files]]
file = "resourcepacks/create-stomified.pw.toml"
hash = "8d24a1dae81462310a51281da2abc19adcf838fb264d5a05dd3774d245cc233e"
metafile = true
