#.
#Migrate copycats to Create: Copycats+ when they receive a block update
migrateCopycatsOnBlockUpdate = true
#.
#Migrate copycats to Create: Copycats+ when their block entities are initialized
migrateCopycatsOnInitialize = true

#.
#Enable/disable features. Values on server override clients
[features]
	copycat_stairs = false
	inverted_clutch = false
	cross_connector = false
	copycat_fence = false
	fluid_vessel = false
	parallel_gearbox = false
	copycat_slab = false
	six_way_gearbox = false
	copycat_vertical_step = false
	copycat_beam = false
	inverted_gearshift = false
	copycat_board = false
	inventory_access_port = false
	copycat_block = false
	item_silo = false
	freewheel_clutch = false
	sequenced_pulse_generator = false
	inventory_bridge = false
	copycat_fence_gate = false
	centrifugal_clutch = false
	brass_gearbox = false
	kinetic_battery = false
	copycat_wall = false
	encased_chain_cogwheel = false
	#.
	kinetic_bridge = true
	empty_fan_catalyst = true
	redstone_link_wildcard = true
	overstress_clutch = true
	brake = true
	large_crank_wheel = true
	crank_wheel = true
	shear_pin = true
	linked_transmitter = true

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#.
	#All kinetic components, such as gearboxes and crank wheels
	kinetic = true
	#.
	#All redstone components, such as linked transmitter and sequenced pulse generator
	redstone = true
	#.
	#All components related to item and fluid transport
	logistics = true
	#.
	#All copycats (Install Create: Copycats+ to upgrade)
	copycats = true
	#.
	#All building palette blocks
	palette = true
