name = "Blueprint"
author = "ItsPercent"
version = "3.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdba908bfae1ad4867f02bfc52fa33cffe759a5c5ecde514c0ca454d2c157634"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
