name = "Blueprint"
author = "ItsPercent"
version = "3.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8813a21c886c3d19ceb453af31ce22d70131dc288567ac191dfad657fac7cf2d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
